

### REST Client plug-in must be installed 
### developed by Huachao Mao

### ------------------------------------------------------------------------------------

### define service setting 
@DataEndPoint = http://localhost:3099/api/patients



### ------------------------------------------------------------------------------------
### get all data 
GET {{DataEndPoint}}
Content-Type: application/json


### ------------------------------------------------------------------------------------
### save
POST {{DataEndPoint}}
Content-Type: application/json

{
    "name": "Thaw Dar",
    "dateOfYear": "1997",
    "age": 23,
    "address": "115, xx Pazundaung Pazundaung Pazundaung",
    "mobileNo": "09 3456789",
    "date": "2020/06/02",
    "dateOfBirth": "2019/04/21"
  }

### ------------------------------------------------------------------------------------
### update
PUT {{DataEndPoint}}/5ef17cb6d87803364880ef07
Content-Type: application/json

{
    "name": "Thaw Dar",
    "dateOfYear": "1997",
    "age": 23,
    "address": "115, xx Pazundaung Pazundaung Pazundaung",
    "mobileNo": "09 3456789",
    "date": "2020/06/02",
     "dateOfBirth": "2019/05/27"
  }

### ------------------------------------------------------------------------------------
### delete
DELETE  {{DataEndPoint}}/5ed71b8daaf3723bfc4b231a
Content-Type: application/json


### ------------------------------------------------------------------------------------
### get by id 
GET {{DataEndPoint}}/5ed4c66d9daab60bcc7a9bb4
Content-Type: application/json


### ------------------------------------------------------------------------------------
