
### REST Client plug-in must be installed 
### developed by Huachao Mao

### ------------------------------------------------------------------------------------

### define service setting 
@DataEndPoint = http://localhost:3099/api/records


### ------------------------------------------------------------------------------------
### get all data 
GET {{DataEndPoint}}
Content-Type: application/json


### ------------------------------------------------------------------------------------
### find by by patientId // return array for all records by patientId //
GET {{DataEndPoint}}/findByPatientId/5edb4474fbc65c33f0a4f041
Content-Type: application/json


### ------------------------------------------------------------------------------------
### save
POST {{DataEndPoint}}
Content-Type: application/json

{
    "date": "2020/06/02", 
    "fee": 7000,
    "description": "ill ",
    "medicine": "c-vid barmiton",  
    "nextAppointmentDate": null,
    "patientId": "5ef1d294cbdb523770553382"    
  }

  
### ------------------------------------------------------------------------------------
### update
PUT {{DataEndPoint}}/5edb495f675c310e0c056ebc
Content-Type: application/json

{
    "date": "2020/06/04", 
    "fee": 7000,
    "description": "ill ",
    "medicine": "c-vid barmiton",  
    "nextAppointmentDate": "2020/06/20",
    "patientId": "5ed5f3a02a2f2046b0ed3a3a"    
  }


### ------------------------------------------------------------------------------------
### delete
DELETE  {{DataEndPoint}}/5edb4472fbc65c33f0a4f040
Content-Type: application/json


### ------------------------------------------------------------------------------------
### get by id 
GET {{DataEndPoint}}/5edb4472fbc65c33f0a4f040
Content-Type: application/json


### ------------------------------------------------------------------------------------
